### ISSUE TITLE
Do not tokenize on dashes

### ISSUE THREAD

**Issue by ajo2995** [warelab/gramene-solr#4]
Some genes only have their names in the gene description, for example QSH-1 in oryza sativa japonica (OS01G0848400).

This will require some analysis to see how well we can identify gene labels from free text. Genes with a non-id name or a set of single word synonoms can be used as a test set.

**Comment by mycrobe** [comment]
It seems to me the correct approach to this is:
1. Fix the source data. This is not our problem.
2. See point 1.
3. Make [this search](http://search.gramene.org/#%7B%22text:qsh-1%20OR%20description:qsh-1%22:%7B%22category%22:%22Gene%22,%22display_name%22:%22All%20genes%20that%20contain%20the%20word%20%5C%22qsh-1%5C%22%22,%22fq%22:%22text:qsh-1%20OR%20description:qsh-1%22%7D%7D) work as expected by not tokenizing on the '-'.

**Comment by mycrobe** [comment]
We should _NOT_ attempt to extract IDs from freetext fields. That way lies madness.

**Comment by ajo2995** [comment]
That sounds tractable. I'll test drive another text field type with the comment 

> Can insert dashes in the wrong place and still match

**Comment by ajo2995** [comment]
I could also split descriptions on white space and add words that have at least 1 digit and 1 letter to the _terms field so they get into suggestions
